// This file was autogenerated by js/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../sector8/client.js', ['sector8.client'], ['goog.functions', 'primus', 'sector8.net', 'sector8.ui.ui']);
goog.addDependency('../../../sector8/core.js', ['sector8.core'], ['util.logger']);
goog.addDependency('../../../sector8/map.js', ['sector8.map'], ['util.make_getters_setters']);
goog.addDependency('../../../sector8/match.js', ['sector8.match'], []);
goog.addDependency('../../../sector8/net.js', ['sector8.net'], ['goog.asserts']);
goog.addDependency('../../../sector8/old/classloader.js', ['sector8.classloader'], ['sector8.core']);
goog.addDependency('../../../sector8/old/db.js', ['sector8.db'], ['goog.asserts', 'sector8.core']);
goog.addDependency('../../../sector8/old/sectoid.js', ['sector8.sectoid'], ['util.make_getters_setters']);
goog.addDependency('../../../sector8/old/watchable.js', ['sector8.watchable'], ['goog.asserts', 'sector8.core']);
goog.addDependency('../../../sector8/primus.js', ['primus'], []);
goog.addDependency('../../../sector8/server.js', ['sector8.server'], ['goog.functions', 'sector8.core', 'sector8.map', 'sector8.session', 'sector8.user']);
goog.addDependency('../../../sector8/session.js', ['sector8.session'], ['goog.asserts', 'sector8.net']);
goog.addDependency('../../../sector8/ui/lobby.js', ['sector8.ui.lobby'], ['goog.dom', 'goog.functions']);
goog.addDependency('../../../sector8/ui/login.js', ['sector8.ui.login'], ['goog.async.Throttle', 'goog.dom', 'goog.functions', 'sector8.user', 'util.make_children_obj']);
goog.addDependency('../../../sector8/ui/match.js', ['sector8.ui.match'], ['goog.dom', 'goog.functions', 'sector8.map', 'sector8.sectoid']);
goog.addDependency('../../../sector8/ui/ui.js', ['sector8.ui.ui'], ['goog.functions', 'sector8.ui.login']);
goog.addDependency('../../../sector8/user.js', ['sector8.user'], ['sector8.core', 'util.make_getters_setters']);
goog.addDependency('../../../util/class.js', ['util.class'], ['goog.asserts']);
goog.addDependency('../../../util/logger.js', ['util.logger'], ['goog.asserts']);
goog.addDependency('../../../util/make_children_obj.js', ['util.make_children_obj'], []);
goog.addDependency('../../../util/make_getters_setters.js', ['util.make_getters_setters'], []);
