// This file was autogenerated by js/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../sector8/board.js', ['sector8.board'], []);
goog.addDependency('../../../sector8/classloader.js', ['sector8.classloader'], ['sector8.core']);
goog.addDependency('../../../sector8/core.js', ['sector8.core'], ['sector8.net', 'util.logger']);
goog.addDependency('../../../sector8/db.js', ['sector8.db'], ['goog.asserts', 'sector8.core']);
goog.addDependency('../../../sector8/game.js', ['sector8.game'], ['sector8.login']);
goog.addDependency('../../../sector8/lobby.js', ['sector8.lobby'], ['goog.dom', 'goog.functions']);
goog.addDependency('../../../sector8/login.js', ['sector8.login'], ['goog.async.Throttle', 'goog.dom', 'sector8.user', 'util.make_children_obj']);
goog.addDependency('../../../sector8/map.js', ['sector8.map'], ['util.make_getters_setters']);
goog.addDependency('../../../sector8/match.js', ['sector8.match'], ['goog.dom', 'goog.functions', 'sector8.map', 'sector8.sectoid']);
goog.addDependency('../../../sector8/net.js', ['sector8.net'], ['goog.asserts', 'primus']);
goog.addDependency('../../../sector8/primus.js', ['primus'], []);
goog.addDependency('../../../sector8/sectoid.js', ['sector8.sectoid'], ['util.make_getters_setters']);
goog.addDependency('../../../sector8/server.js', ['sector8.server'], ['sector8.core']);
goog.addDependency('../../../sector8/user.js', ['sector8.user'], ['sector8.core', 'util.make_getters_setters']);
goog.addDependency('../../../sector8/watchable.js', ['sector8.watchable'], ['goog.asserts', 'sector8.core']);
goog.addDependency('../../../util/logger.js', ['util.logger'], ['goog.asserts']);
goog.addDependency('../../../util/make_children_obj.js', ['util.make_children_obj'], []);
goog.addDependency('../../../util/make_getters_setters.js', ['util.make_getters_setters'], []);
